

(* keep_hierarchy = "yes" *)
module datapath #(
    parameter width=32,
              instr_mem_addr_width=9,
              instr_mem_depth=512,
                regfile_depth=32,
                data_width=32,
                data_mem_depth=512,
                data_mem_addr_width=9,
                regfile_address_width=5

    )
    (
        input clk,reset,
        input debug_en, // for debugging purpose
        input [regfile_address_width-1:0] regfile_debug_addr, // for debugging purpose
        output [data_width-1:0] debug_regfile_data, // for debugging purpose
        output [data_width-1:0] debug_pc


    );
    localparam ctrl_signal_width = 11; // total number of control signals generated by control unit
    // internal pipeline register control signals generated by hazard detection unit;
    wire flush_if_id,stall_if_id,
         flush_id_ex,stall_id_ex,
         flush_ex_mem,stall_ex_mem,
         flush_mem_wb,stall_mem_wb;
    wire instr_valid_id; // to check the validity of instr in id stage, as it may be 
                         // due to registered ram output which may have been flushed 
                         // if this goes low then we can consider the instruction in id stage as invalid and not generate control signals for it to avoid executing wrong instructions
                         // so it must be generated in if_addr stage and stored in if_addr/if_data pipeline register and passed to if_data stage where
                         // and passed to id stage where we can flush the instruction so it act as an
                         // actual bubble
    wire instr_valid_if_addr,instr_valid_if_data;
    assign instr_valid_if_addr = 1'b1; // we can consider all fetched instructions as valid in if_addr stage because we will handle flushing in the pipeline registers
    // hdu stall signal
    wire stall_hdu;// this signal will be high when hdu detects a hazard and needs to stall the pipeline and flush if/id pipeline register
    assign flush_if_id = branch_taken|is_jump_ex|reset; // when branch is taken we need to flush the if/id pipeline register to avoid executing wrong instructions
    assign flush_id_ex = branch_taken|is_jump_ex|stall_hdu|reset; // when branch is taken we need to flush the id/ex pipeline register to avoid executing wrong instructions
    assign stall_id_ex = debug_en ; // we don't need to stall the id/ex pipeline register because when there is a hazard we will flush it and insert a bubble in the pipeline
    assign flush_ex_mem = reset;
    assign flush_mem_wb = reset;
    assign stall_ex_mem = debug_en;
    assign stall_mem_wb = debug_en; // ! have to handle bram latency
    assign debug_pc=pc_curr & {4{debug_en}};
//    assign debug_wb=regfile_data_wb;
//    assign debug_alu=alu_result;
//    assign instruction_id=valid_instr;
//    assign debug_pc_id=pc_id;
//    assign debug_data_mem_in=mem_shifted_store_data;
//    assign debug_data_mem_out=mem_data_wb;
//    assign debug_pc_ex=pc_ex;
//    assign debug_pc_mem=pc_plus_4_mem-4;
//    assign debug_pc_wb=pc_plus_4_wb-4;
//    assign mem_en_rd_wrbar=mem_rd_or_wr_bar_mem;
//    assign debug_we=we;
//    assign alu_ctrl=alu_control_ex;
    // hazard detection unit instance
    hazard_detection_unit hdu(
        .rd_addr_ex(rd_addr_ex),
        .rs1_addr_id(rs1_addr),
        .rs2_addr_id(rs2_addr_ins),
        .mem_en_ex(mem_en_ex),
        .mem_rd_or_wr_bar_ex(mem_rd_or_wr_bar_ex),
        .stall(stall_hdu)
    );
    // forwarding handler unit signals
    wire [1:0] forward_in1,forward_in2; // forwarding control signals
    forwarding_handler fwd_handler(
        .rd_addr_mem(rd_addr_mem),
        .rs1_addr_ex(rs1_addr_ex),
        .rs2_addr_ex(rs2_addr_ex),
        .rd_addr_wb(rd_addr_wb),
        .reg_write_en_mem(reg_write_en_mem),
        .reg_write_en_wb(reg_write_en_wb),
        .forward_in1(forward_in1),
        .forward_in2(forward_in2)
    );

    assign stall_if_id = stall_hdu|debug_en; // when there is a hazard we need to stall the if/id pipeline register to avoid fetching new instructions
    // pipeline register outputs:
    // if.addr/if.data register outputs
    wire [width-1:0] pc_if_data,pc_plus_4_if_data;
    // IF/ID pipeline register outputs
    wire [width-1:0] instr_id,pc_id,pc_plus_4_id;

    // id/ex pipeline register outputs
    wire [width-1:0] rs1_ex,rs2_ex,pc_ex,pc_plus_4_ex;
    wire [2:0] funct3_ex;
    wire [12:0] imm_12_ex;
    wire [20:0] imm_20_UJ_type_ex;
    wire [regfile_address_width-1:0] rs1_addr_ex,rs2_addr_ex,rd_addr_ex;
    // ex/mem pipeline register outputs
    wire [width-1:0] alu_result_mem,rs2_mem,pc_plus_4_mem;
    wire [2:0] funct3_mem;
    wire [regfile_address_width-1:0] rs1_addr_mem,rs2_addr_mem,rd_addr_mem;
    // mem/wb pipeline register outputs
    wire [width-1:0] alu_result_wb,mem_data_wb,pc_plus_4_wb,wb_data_ex;
    wire [2:0] funct3_wb;
    wire [regfile_address_width-1:0] rd_addr_wb,rs1_addr_wb,rs2_addr_wb;
    // internal signals
(* mark_debug = "true" *)    wire [width-1:0] regfile_data_wb; // mark debug is for preventing the signal from getting optimized away bu synthesizer by connecting it to an ila core
    wire branch_taken;
    //control signals generated by instruction decoder
    wire alu_src_sel,reg_write_en,mem_en,mem_rd_or_wr_bar,is_branch,is_jump,pc_offset_src,reg_write_sel;
    wire [1:0] sign_ext_12bit_src;
    wire [3:0] alu_control;
    // control signals stored in pipeline registers
    // id/ex stage control signals
    wire alu_src_sel_ex,reg_write_en_ex,mem_en_ex,mem_rd_or_wr_bar_ex,is_branch_ex,is_jump_ex,pc_offset_src_ex,reg_write_sel_ex;
    wire [3:0] alu_control_ex;
    // ex/mem stage control signals
    wire reg_write_en_mem,mem_en_mem,mem_rd_or_wr_bar_mem,is_jump_mem,reg_write_sel_mem;
    // mem/wb stage control signals
    wire reg_write_en_wb,is_jump_wb,reg_write_sel_wb;
    // execute stage internal signals
    wire [width-1:0] alu_in2,alu_result,forwarded_rs1_data,forwarded_rs2_data;
    // IF stage
    //========================================================================================
    // internal signals if_addr stage registers and wires to connect different modules
    wire [width-1:0] pc_next,pc_curr,pc_plus_4,pc_next_target;
    wire [width-1:0] instr_raw; // instruction fetched from instruction memory to be stored in if/id pipeline register
    wire [width-1:0] pc_im; 
    assign pc_im = stall_if_id ? pc_if_data : pc_curr; // when there is a stall we need to keep the pc value same to avoid fetching new instructions and when there is no stall we can update the pc value to fetch new instructions
    //assign instr_id = flush_if_id ? 32'b0 : instr_raw; // if there is a flush we need to insert a bubble in the pipeline by setting instruction to nop (which is represented by all 0s)                          
    mux4_to_1  #(
        .width(32)
    )mux_pc
    (
        .a(pc_plus_4),// pc+4
        .b(pc_next_target),// for branches  
        .c(alu_result), // for jump and link register instruction(pc=R[rs1]+imm)
        .d(pc_next_target), // for jal instruction (pc=pc+imm)
        .sel({is_jump_ex,pc_offset_src_ex|branch_taken}),
        .out(pc_next)
    );
    // pc register
    pipo_reg #(width) PC (
        .clk(clk),
        .rst(reset),
        .en(~stall_if_id),
        .in(pc_next),
        .out(pc_curr)
    );
    // pc_incrementer
    pc_adder #(
        .width(width)
    ) pc_inc(
        .curr_pc(pc_curr),
        .offset(32'd4),
        .pc_next(pc_plus_4)
    );
    // IF.addr/if.data pipeline register
    pipeline_reg #(
        .width(2*width+1), // we need to store pc,pc+4 and instr_valid signal in this pipeline register
        .reset(32'b0)
    ) IFaddr_IFdata (
        .clk(clk),
        .rst(reset),
        .en(~stall_if_id),
        .flush(flush_if_id),
        .in({pc_plus_4,pc_curr,instr_valid_if_addr}),
        .out({pc_plus_4_if_data,pc_if_data,instr_valid_if_data})
    );
    //instruction memory
    instr_mem #(
        .addr_width(instr_mem_addr_width),
        .data_width(data_width),
        .depth(instr_mem_depth)
    ) IM (
        .clk(clk),
        .addr(pc_im[10:2]), 
        .data_out(instr_raw)
    );
    // instruction register to hold the fetched instruction and pass it to the next stage (id stage)
    pipeline_reg #(
        .width(3*width+1) // we need to store the instruction, pc, pc+4, and instr_valid signal
        ) IFID_instr (
        .clk(clk),
        .rst(reset),
        .en(~stall_if_id),
        .flush(flush_if_id),
        .in({instr_raw,pc_plus_4_if_data,pc_if_data,instr_valid_if_data}), // we need to pass pc and pc+4 to the next stage for branch target calculation and jal instruction
        .out({instr_id,pc_plus_4_id,pc_id,instr_valid_id})
    );
    
    // instruction decode stage
    //========================================================================================
    //internal signals for id_stage
(* mark_debug = "true" *)    wire [width-1:0] valid_instr= instr_valid_id? instr_id: 32'b0; // if the instruction in id stage is not valid we can consider it as nop (which is represented by all 0s) to avoid generating control signals for it and executing wrong instructions
    wire [width-1:0] rs1_data, rs2_data;
    wire [4:0] rs1_addr_ins,rs2_addr_ins,rd_addr,rs1_addr; 
    wire [12:0] imm_12_i_type,imm_12_s_type,imm_12,imm_12_SB_type; // 12 bits signed immediates
    wire [20:0] imm_20_UJ_type;// 21 bits shifted immediate for uj type
    wire [6:0] opcode; // opcode for control unit
    wire [2:0] funct3; // funct3 for control unit
    wire [6:0] funct7;  // funct7 for control unit
    assign rs1_addr= debug_en? regfile_debug_addr:rs1_addr_ins;
    assign debug_regfile_data=debug_en? rs1_data:32'b0;
    assign rs1_addr_ins=valid_instr[19:15];
    assign rs2_addr_ins=valid_instr[24:20];
    assign rd_addr = valid_instr[11:7];
    assign opcode = valid_instr[6:0]; // opcode for control unit
    assign funct3 = valid_instr[14:12]; // funct3 for control unit
    assign funct7 = valid_instr[31:25]; // funct7 for control unit
    assign imm_20_UJ_type={valid_instr[31],valid_instr[19:12],valid_instr[20],valid_instr[30:21],1'b0};
    assign imm_12_i_type = {valid_instr[31],valid_instr[31:20]};// i type immediate is made 13 bit to make it equal to width of sbtype and s type immediates after shifting left by 1 bit to make it 12 bit immediate for branch target calculation
    assign imm_12_s_type = {valid_instr[31:25],valid_instr[11:7]};// s  type immediate is made 13 bit to make it equal to width of sbtype and s type immediates after shifting left by 1 bit to make it 12 bit immediate for branch target calculation
    assign imm_12_SB_type = {valid_instr[31],valid_instr[7],valid_instr[30:25],valid_instr[11:8],1'b0};//sb type is shifted left by  bit
    // instruction decoder
    instruction_decoder instr_dec(
    .opcode(opcode),
    .funct3(funct3),
    .funct7(funct7),
    .alu_in_sel(alu_src_sel),
    .reg_write_en(reg_write_en),
    .reg_write_sel(reg_write_sel),
    .mem_en(mem_en),
    .mem_rd_or_wr_bar(mem_rd_or_wr_bar),
    .sign_ext_sel_12bit(sign_ext_12bit_src),
    .is_branch(is_branch),
    .alu_control(alu_control),
    .is_jump(is_jump),
    .sign_ext_sel_20bit(pc_offset_src)
    );
    //register file
    regfile #(
        .reg_width(width),
        .addr_width(regfile_address_width),
        .depth(regfile_depth)
    ) RF (
        .clk(clk),
        .rs1_addr(rs1_addr),
        .rs2_addr(rs2_addr_ins),
        .rd_addr(rd_addr_wb),
        .rd_data(regfile_data_wb),
        .reg_write(reg_write_en_wb),
        .rs1_data(rs1_data),
        .rs2_data(rs2_data)
    );
    //sign extension source mux ofr 12 bit immediate
     mux3_to_1  #(
        .width(13)
    )mux_imm
    (
        .a(imm_12_i_type),
        .b(imm_12_s_type),
        .c(imm_12_SB_type),
        .sel(sign_ext_12bit_src),
        .out(imm_12)
    );
    // id/ex pipeline register
    pipeline_reg #(
        .width(4*width+3+12+21+13+regfile_address_width*3) // total width of all signals to be stored in id/ex pipeline register(pc,pc+4,rs1_data,rs2_data,funct3,imm_12,imm_20 and control signals)
    ) ID_EX (
        .clk(clk),
        .rst(reset),
        .en(~stall_id_ex),
        .flush(flush_id_ex),
        .in({pc_plus_4_id,pc_id,rs1_data,rs2_data,rs1_addr_ins,rs2_addr_ins,rd_addr,funct3,imm_12,imm_20_UJ_type,alu_src_sel,reg_write_en,mem_en,mem_rd_or_wr_bar,is_branch,is_jump,pc_offset_src,reg_write_sel,alu_control}),
        .out({pc_plus_4_ex,pc_ex,rs1_ex,rs2_ex,rs1_addr_ex,rs2_addr_ex,rd_addr_ex,funct3_ex,imm_12_ex,imm_20_UJ_type_ex,alu_src_sel_ex,reg_write_en_ex,mem_en_ex,mem_rd_or_wr_bar_ex,is_branch_ex,is_jump_ex,pc_offset_src_ex,reg_write_sel_ex,alu_control_ex})
        
    );
    // execute stage
    //========================================================================================
    wire [width-1:0] sign_ext_imm_12, sign_ext_imm_20; 
    wire [width-1:0] pc_offset;                 
    wire alu_zero_flag;    

    // 12bit immediates sign extension unit
    // sign extension unit for 12 bit immediates
    sign_extender #(
        .input_width(13)
    ) sign_extender_module_12bit (
        .in(imm_12_ex),
        .out(sign_ext_imm_12)
    );
    // sign extension unit for 20 bit immediates
    sign_extender #(
        .input_width(21)
    ) sign_extender_module_20bit (
        .in(imm_20_UJ_type_ex),// 
        .out(sign_ext_imm_20)
    );
    // alu input2 mux
    mux #(
        .width(width)
    ) alu_src_mux (
        .a(forwarded_rs2_data), // for R-type instructions
         .b(sign_ext_imm_12),// for itype immediates (brannch and jalr)
        .sel(alu_src_sel_ex),
        .out(alu_in2)
    );
    // forwarding mux for alu input 1
    mux3_to_1 #(
        .width(width)
    ) fwd_mux_in1 (
        .a(rs1_ex),
        .b(alu_result_mem),
        .c(regfile_data_wb),
        .sel(forward_in1),
        .out(forwarded_rs1_data)
    );
    // forwarding mux for alu input 2
    mux3_to_1 #(
        .width(width)
    ) fwd_mux_in2 (
        .a(rs2_ex),
        .b(alu_result_mem),
        .c(regfile_data_wb),
        .sel(forward_in2),
        .out(forwarded_rs2_data)
    );
    // ALU
    alu #(
        .width(width)
    ) ALU(
        .a(forwarded_rs1_data),
        .b(alu_in2),
        .alu_control(alu_control_ex),
        .result(alu_result),
        .zero(alu_zero_flag)
    );
    // branch handler
    branch_handler branch(
        .funct3(funct3_ex),
        .is_zero(alu_zero_flag),
        .is_branch(is_branch_ex),
        .alu_result_lsb(alu_result[0]),
        .branch_taken(branch_taken)
    );
    // pc offset source mux for branch and jump instructions
    mux #(
        .width(width)
    ) pc_offset_mux (
        .a(sign_ext_imm_12),// for itype and immediates (brannch and jalr)
        .b(sign_ext_imm_20), // for uj type immediates (jal)
        .sel(pc_offset_src_ex),
        .out(pc_offset)
    );
   // branch/jump target address calculator
    pc_adder #(
        .width(width)
    ) branch_target_calc(
        .curr_pc(pc_ex),
        .offset(pc_offset),
        .pc_next(pc_next_target)
    );
    // ex/mem pipeline register
    pipeline_reg #(
        .width(3*width+3+5+regfile_address_width*3) // total width of all signals to be stored in ex/mem pipeline register(alu_result,rs2 for store instructions,pc+4 for jal instruction,funct3 for store instructions and control signals)
    ) ex_mem(
        .clk(clk),
        .rst(reset),
        .en(~stall_ex_mem),
        .flush(flush_ex_mem),
        .in({alu_result,forwarded_rs2_data,pc_plus_4_ex,rs1_addr_ex,rs2_addr_ex,rd_addr_ex,funct3_ex,is_jump_ex,reg_write_sel_ex,reg_write_en_ex,mem_en_ex,mem_rd_or_wr_bar_ex}),
        .out({alu_result_mem,rs2_mem,pc_plus_4_mem,rs1_addr_mem,rs2_addr_mem,rd_addr_mem,funct3_mem,is_jump_mem,reg_write_sel_mem,reg_write_en_mem,mem_en_mem,mem_rd_or_wr_bar_mem})
    );
    // mem stage
    //========================================================================================
 (* mark_debug = "true" *)   wire [width-1:0] mem_data,mem_shifted_store_data;
 (* mark_debug = "true" *)   wire [3:0] we; // byte enable signals for data memory
    // lsu
    store_unit #(
        .data_width(width)
    ) su( 
        .funct3(funct3_mem),
        .addr_lsb(alu_result_mem[1:0]),
        .mem_rd_or_wr_bar(mem_rd_or_wr_bar_mem),
        .we(we),
        .data_in(rs2_mem),
        .mem_shifted_store_data(mem_shifted_store_data)
    );
     // data memory
  data_mem #(
        .addr_width(data_mem_addr_width),
        .data_width(data_width),
        .depth(data_mem_depth)
    ) DM (
        .clk(clk),
        .addr(alu_result_mem[10:2]), // word aligned addressing
        // going to handle it later // write enable is active when mem_enable is high and mem_rd_or_wr_bar is low
        .we(we & {4{mem_en_mem & ~mem_rd_or_wr_bar_mem}}), // we need to mask the we signals with mem_en and mem_rd_or_wr_bar signals to make sure that we only write to memory when mem_en is high and mem_rd_or_wr_bar is low (write operation)
        .data_in(mem_shifted_store_data),
        .data_out(mem_data_wb)
    );
    // mem/wb pipeline register
    pipeline_reg #(
        .width(2*width+3+regfile_address_width*3+3) //total width of all signals to be stored in mem/wb pipeline register(alu_result,mem_data,pc+4 for jal instruction and control signals)
    ) mem_wb(
        .clk(clk),
        .rst(reset),
        .en(~stall_mem_wb),
        .flush(flush_mem_wb),
        .in({alu_result_mem,pc_plus_4_mem,rs1_addr_mem,rs2_addr_mem,rd_addr_mem,funct3_mem,is_jump_mem,reg_write_sel_mem,reg_write_en_mem}),
        .out({alu_result_wb,pc_plus_4_wb,rs1_addr_wb,rs2_addr_wb,rd_addr_wb,funct3_wb,is_jump_wb,reg_write_sel_wb,reg_write_en_wb})
    );
    // write back stage
    //========================================================================================
    // load unit for handling different load types and aligning data read from memory
  (* mark_debug = "true" *)  wire [width-1:0] lsu_out; // output of load store unit which will be written back to register file for load instructions
    load_unit #(
        .data_width(width)
    ) load_unit(
        .mem_data(mem_data_wb),
        .funct3(funct3_wb),
        .addr_lsb(alu_result_wb[1:0]),
        .mem_rd_or_wr_bar(1'b1), // for load operations
        .lsu_out(lsu_out)
    );
    // write back data mux
    mux3_to_1 #(
        .width(width)
    ) wb_mux (
        .a(alu_result_wb), // for R-type and I-type arithmetic instructions
        .b(lsu_out), // for load instructions
        .c(pc_plus_4_wb), // for jal instruction
        .sel({is_jump_wb,reg_write_sel_wb}),
        .out(regfile_data_wb)
    );
     
endmodule
