module datapath #(
    parameter width=32,
              instr_mem_addr_width=9,
              instr_mem_depth=512,
                regfile_depth=32,
                data_width=32,
                data_mem_depth=512,
                data_mem_addr_width=9

    )(
        input clk,reset,alu_in_sel,pc_write,mem_enable,mem_rd_wr_bar,reg_write_en,reg_write_sel,
              is_branch,is_jump,sign_ext_sel_20bit,
        input [1:0] sign_ext_sel_12bit,// for immediate selection(I-type or S-type,SB-type)
        input [3:0] alu_control,
        input debug_en, // for debugging purpose
        input [4:0] regfile_debug_addr, // for debugging purpose
        output [width-1:0] debug_regfile_data, // for debugging purpose

        output [6:0] opcode, // opcode for control unit
        output [2:0] funct3, // funct3 for control unit
        output [6:0] funct7  // funct7 for control unit
    );
    // internal signals 
    wire [width-1:0] pc_next,pc_curr,instr,rs1_data,rs2_data,alu_in2,alu_result,
                     mem_data,sign_ext_imm_12,sign_ext_imm_20,alu_in1, regfile_data,lsu_out,mem_shifted_store_data,
                     pc_offset,pc_next_branch,pc_next_instr,sign_ext_imm,regfile_data_wb;
    wire [3:0] we; // write enable signals for data memory generated by lsu
    wire [4:0] rs1_addr,rs2_addr,rd_addr; // sliced indexes of referenced regigsters
    wire [11:0] imm_12_i_type,imm_12_s_type,imm_12,imm_12_SB_type; // 12 bits signed immediates
    wire [19:0] imm_20_UJ_type;// 20 bits immediate for uj type
    
    wire alu_zero_flag,branch_taken;
    assign opcode = instr[6:0]; // opcode for control unit
    assign funct3 = instr[14:12]; // funct3 for control unit
    assign funct7 = instr[31:25]; // funct7 for control unit
    assign rs1_addr = debug_en ? regfile_debug_addr :  instr[19:15];
       // rs1 address(if debug_en is high, use debug address this way we can read any register
       // value by external register address hence know the state) 

    assign rs2_addr = instr[24:20]; // register source 2 address
    assign rd_addr = instr[11:7]; // register destination address 
    assign imm_20_UJ_type={instr[31],instr[19:12],instr[20],instr[30:21],1'b0};

    assign debug_regfile_data = rs1_data ; // for debugging purpose

    // immediate extraction
    assign imm_12_i_type = instr[31:20];
    assign imm_12_s_type = {instr[31:25],instr[11:7]};
    assign imm_12_SB_type = {instr[31],instr[7],instr[30:25],instr[11:8]};

    // mux
    assign sign_ext_imm = sign_ext_sel_20bit? sign_ext_imm_20 :sign_ext_imm_12;
    assign alu_in1= is_jump ? pc_curr : rs1_data; 
    assign alu_in2 = alu_in_sel ? sign_ext_imm : rs2_data;
    assign regfile_data_wb = reg_write_sel ? lsu_out : alu_result; // if reg_write_sel is high , write data from memory else from ALU in write back(no jump)
    assign regfile_data=is_jump? pc_next_instr:regfile_data_wb;
    assign pc_offset_12=sign_ext_imm_12<<1; // for jalr instruction and branch instructions
    assign pc_offset=sign_ext_sel_20bit?sign_ext_imm_20:pc_offset_12;
    // assign pc_next=(branch_taken)? pc_next_branch : pc_next_instr;

    //pc_mux
    mux3_to_1  #(
        .width(32)
    )mux_pc
    (
        .a(pc_next_instr),
        .b(pc_next_branch),
        .c(alu_result), // for jump and link register
        .sel({is_jump,branch_taken}),
        .out(pc_next)
    );
    // pc register
    pipo_reg #(width) PC (
        .clk(clk),
        .rst(reset),
        .en(pc_write),
        .in(pc_next),
        .out(pc_curr)
    );
    // pc_incrementer
    pc_adder #(
        .width(width)
    ) pc_inc(
        .curr_pc(pc_curr),
        .offset(32'h00000004),
        .pc_next(pc_next_instr)
    );
    
    //instruction memory
    instr_mem #(
        .addr_width(instr_mem_addr_width),
        .data_width(data_width),
        .depth(instr_mem_depth)
    ) IM (
        .clk(clk),
        .addr(pc_curr[10:2]), 
        .data_out(instr)
    );
    //register file
    regfile #(
        .reg_width(width),
        .addr_width(5),
        .depth(regfile_depth)
    ) RF (
        .clk(clk),
        .rs1_addr(rs1_addr),
        .rs2_addr(rs2_addr),
        .rd_addr(rd_addr),
        .rd_data(regfile_data),
        .reg_write(reg_write_en),
        .rs1_data(rs1_data),
        .rs2_data(rs2_data)
    );
    // sign extension unit for 12 bit immediates
    sign_extender #(
        .input_width(12)
    ) sign_extender_module_12bit (
        .in(imm_12),
        .out(sign_ext_imm_12)
    );
    // sign extension unit for 20 bit immediates
    sign_extender #(
        .input_width(20)
    ) sign_extender_module_20bit (
        .in(imm_20_UJ_type),// 
        .out(sign_ext_imm_20)
    );
    //mux3_to_1
    mux3_to_1  #(
        .width(12)
    )mux_imm
    (
        .a(imm_12_i_type),
        .b(imm_12_s_type),
        .c(imm_12_SB_type),
        .sel(sign_ext_sel_12bit),
        .out(imm_12)// do mux sign extension signal connection with alu and pc adder
    );
    // branch/jump target address calculator
    pc_adder #(
        .width(width)
    ) branch_target_calc(
        .curr_pc(pc_curr),
        .offset(pc_offset),
        .pc_next(pc_next_branch)
    );
    // ALU
    alu #(
        .width(width)
    ) ALU(
        .a(alu_in1),
        .b(alu_in2),
        .alu_control(alu_control),
        .result(alu_result),
        .zero(alu_zero_flag)
    );
    branch_handler branch(
        .funct3(funct3),
        .is_zero(alu_zero_flag),
        .is_branch(is_branch),
        .alu_result_lsb(alu_result[0]),
        .branch_taken(branch_taken)
    );
    // lsu
    load_store_unit #(
        .data_width(width)
    ) lsu( 
        .mem_data(mem_data),
        .funct3(funct3),
        .addr_lsb(alu_result[1:0]),
        .mem_rd_or_wr_bar(mem_rd_wr_bar),
        .we(we),
        .lsu_out(lsu_out),
        .data_in(rs2_data),
        .mem_shifted_store_data(mem_shifted_store_data)
    );
    // data memory
    data_mem #(
        .addr_width(data_mem_addr_width),
        .data_width(data_width),
        .depth(data_mem_depth)
    ) DM (
        .clk(clk),
        .addr(alu_result[10:2]), // word aligned addressing
        .enable(mem_enable),
        .rd(mem_rd_wr_bar),
        // going to handle it later // write enable is active when mem_enable is high and mem_rd_or_wr_bar is low
        .we(we),
        .data_in(mem_shifted_store_data),
        .data_out(mem_data)
    );
    

endmodule